#!/usr/bin/env python3
"""
Bundle the deprecated ``pipe_logic.py`` and ``api/prompts/*.md`` into a single
``pipe_logic_embedded.py`` for OpenWebUI (legacy / offline installs).

Preferred path for production: run the FastAPI service (``api/``) and import
``api/pipe/pipe.py`` in OpenWebUI instead of this embedded artifact.

Usage (from repo root):
    python api/pipe/generate-logic-pipe.py
"""

from __future__ import annotations

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

PIPE_DIR = Path(__file__).resolve().parent
API_DIR = PIPE_DIR.parent
PIPE_SOURCE = PIPE_DIR / "pipe_logic.py"
PROMPTS_DIR = API_DIR / "prompts"
OUTPUT = PIPE_DIR / "pipe_logic_embedded.py"

PROMPT_SECTION_START = (
    "# ---------------------------------------------------------------------------\n"
    "# Prompt loading"
)
PROMPT_SECTION_END = (
    "# ---------------------------------------------------------------------------\n"
    "# Utilities"
)


def collect_prompts() -> dict[str, str]:
    """Read all markdown prompts keyed by path relative to prompts/."""
    prompts: dict[str, str] = {}
    for path in sorted(PROMPTS_DIR.rglob("*.md")):
        key = path.relative_to(PROMPTS_DIR).as_posix()
        prompts[key] = path.read_text(encoding="utf-8").strip()
    return prompts


def build_embedded_prompts_block(prompts: dict[str, str]) -> str:
    prompts_literal = json.dumps(prompts, ensure_ascii=False, indent=4)
    return f"""# ---------------------------------------------------------------------------
# Embedded prompts (generated — do not edit; edit api/prompts/*.md and rebuild)
# ---------------------------------------------------------------------------

EMBEDDED_PROMPTS: dict[str, str] = {prompts_literal}


def _load_prompt(relative_path: str) -> str:
    \"\"\"Return embedded prompt text by relative path key.\"\"\"
    try:
        return EMBEDDED_PROMPTS[relative_path]
    except KeyError as exc:
        raise KeyError(f"Embedded prompt not found: {{relative_path!r}}") from exc


def get_core_prompt() -> str:
    return _load_prompt("core.md")


def get_persona_prompt(persona: PersonaId) -> str | None:
    if persona == "none":
        return None
    if persona not in SUPPORTED_PERSONAS:
        return None
    return _load_prompt(f"personas/{{persona}}.md")


def get_intent_detection_prompt() -> str:
    return _load_prompt("intent_detection.md")


def get_reflection_prompt() -> str:
    template = _load_prompt("reflection.md")
    return template.replace("{{{{CORE_PROMPT}}}}", get_core_prompt())
"""


def strip_pathlib_dependency(source: str) -> str:
    source = source.replace("from pathlib import Path\n", "")
    source = re.sub(
        r"\n# Prompts live under api/prompts/ \(sibling of this package directory\)\.\n"
        r"PROMPTS_DIR = Path\(__file__\)\.resolve\(\)\.parent\.parent / \"prompts\"\n",
        "\n",
        source,
        count=1,
    )
    # Fallback for older / alternate PROMPTS_DIR lines.
    source = re.sub(
        r"\nPROMPTS_DIR = Path\(__file__\)(?:\.resolve\(\))?\.parent(?:\.parent)? / \"prompts\"\n",
        "\n",
        source,
        count=1,
    )
    return source


def inject_generated_header(source: str) -> str:
    header = (
        "# AUTO-GENERATED by api/pipe/generate-logic-pipe.py — do not edit manually.\n"
        f"# Generated at: {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
        "# Source: api/pipe/pipe_logic.py + api/prompts/\n"
        "# Rebuild: python api/pipe/generate-logic-pipe.py\n"
        "# DEPRECATED: prefer api/pipe/pipe.py + the standalone API service.\n"
    )
    if not source.startswith('"""'):
        return header + "\n" + source

    docstring_end = source.index('"""', 3) + 3
    return source[:docstring_end] + "\n\n" + header + source[docstring_end + 1 :].lstrip("\n")


def build_embedded_pipe() -> str:
    source = PIPE_SOURCE.read_text(encoding="utf-8")
    start = source.find(PROMPT_SECTION_START)
    end = source.find(PROMPT_SECTION_END)

    if start == -1 or end == -1 or end <= start:
        raise ValueError(
            "Could not find prompt loading section markers in pipe_logic.py"
        )

    prompts = collect_prompts()
    if not prompts:
        raise ValueError(f"No .md prompts found under {PROMPTS_DIR}")

    embedded_block = build_embedded_prompts_block(prompts)
    output = source[:start] + embedded_block + "\n\n" + source[end:]
    output = strip_pathlib_dependency(output)
    return inject_generated_header(output)


def main() -> int:
    if not PIPE_SOURCE.is_file():
        print(f"error: missing {PIPE_SOURCE}", file=sys.stderr)
        return 1
    if not PROMPTS_DIR.is_dir():
        print(f"error: missing {PROMPTS_DIR}", file=sys.stderr)
        return 1

    try:
        content = build_embedded_pipe()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    OUTPUT.write_text(content, encoding="utf-8")
    prompt_count = len(collect_prompts())
    print(
        f"Wrote {OUTPUT.relative_to(API_DIR.parent)} "
        f"({prompt_count} prompts embedded) [DEPRECATED artifact]"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
